schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight
  branches:
    include:
      - master

trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- powershell: Install-Module au
  displayName: 'Install the AU Powershell Module'
- task: PowerShell@2
  inputs:
    filePath: 'update.ps1'
    workingDirectory: '$(Pipeline.Workspace)\wvd-agent\'
